### ISSUE TITLE
Installation / Executing mlnlearn

### ISSUE THREAD

**Issue by SND8041** [opcode81/ProbCog#10]
Hello,
I have installed probcog, the latest version, and I am trying to execute the command mlnlearn but getting the following error:

C:\probcog>mlnlearn
Warning: Failed to import SciPy/NumPy (http://www.scipy.org)! Parameter learning with PyMLNs is disabled.
Warning: Failed to import SciPy/NumPy (http://www.scipy.org)! Parameter learning with the MLN module is disabled.
Traceback (most recent call last):
  File "C:\probcog\src\main\python\mlnLearningTool.py", line 32, in <module>
    import MLN
  File "C:\probcog\src\main\python\MLN\__init__.py", line 26, in <module>
    from MarkovLogicNetwork import *
  File "C:\probcog\src\main\python\MLN\MarkovLogicNetwork.py", line 92, in <module>
    import learning
  File "C:\probcog\src\main\python\MLN\learning\__init__.py", line 7, in <module>
    from BPLL import *
  File "C:\probcog\src\main\python\MLN\learning\BPLL.py", line 29, in <module>
    import numpy
ImportError: No module named numpy

Can you help me what's going on. Also, the blnlearn tool seems working fine.

Best regards,
Syed

**Comment by opcode81** [comment]
MLN learning requires the Python packages numpy and scipy. You can install them using your package manager, e.g. pip (`pip install numpy` and `pip install scipy`).
