### ISSUE TITLE
Exception while trying to use netEd tool with Ubuntu 18.04

### ISSUE THREAD

**Issue by opcode81** [opcode81/ProbCog#26]
I also wanted to add that I got the following exception while trying to learn the netEd tool with Ubuntu 18.04 and following java version:

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

java.lang.NullPointerException
	at org.eclipse.swt.widgets.TabFolder.gtk_switch_page(Unknown Source)
	at org.eclipse.swt.widgets.Widget.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.gtk.OS._gtk_widget_show(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_widget_show(Unknown Source)
	at org.eclipse.swt.widgets.TabFolder.createItem(Unknown Source)
	at org.eclipse.swt.widgets.TabItem.createWidget(Unknown Source)
	at org.eclipse.swt.widgets.TabItem.<init>(Unknown Source)
	at edu.ksu.cis.bnj.gui.GUIWindow.run(GUIWindow.java:902)
	at edu.ksu.cis.bnj.gui.GUIThread.run(GUIThread.java:66)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Unknown Source)
	at org.eclipse.swt.widgets.Display.syncExec(Unknown Source)
	at edu.ksu.cis.bnj.gui.GUIWindow.open(GUIWindow.java:659)
	at edu.ksu.cis.bnj.gui.GUIWindow.open(GUIWindow.java:665)
	at probcog.bayesnets.core.BeliefNetworkEx.show(BeliefNetworkEx.java:691)
	at probcog.BNJ.main(BNJ.java:54)

Thanks a lot!

_Originally posted by @mcubuktepe in https://github.com/opcode81/ProbCog/issues/25#issuecomment-626413056_

**Comment by opcode81** [comment]
@mcubuktepe, please post the SWT dependency that you have in your pom.xml.

**Comment by mcubuktepe** [comment]
Hi, I am attaching the txt version of the pom.xml file as Github does not support attaching XML files.
[pom.txt](https://github.com/opcode81/ProbCog/files/4610797/pom.txt)

These are the lines of the pom.xml file that include SWT information.
		<repository>
			<id>swt-repo</id>
			<url>https://raw.githubusercontent.com/maven-eclipse/swt-repo/master/</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>org.eclipse.swt</groupId>
			<artifactId>org.eclipse.swt.gtk.linux.x86_64</artifactId>
			<version>4.4</version>
		</dependency>

**Comment by opcode81** [comment]
Please check whether changing the version to 4.6.1 and subsequently rerunning map_apps fixes the problem.

**Comment by opcode81** [comment]
Most likely, the issue is due to a [problem in SWT itself](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486069).

**Comment by mcubuktepe** [comment]
Hi, I was able to run netEd, but I got the following log in the terminal while launching netEd, I wanted to check if this is a problem
[netedlog.txt](https://github.com/opcode81/ProbCog/files/4611523/netedlog.txt).

**Comment by opcode81** [comment]
Was being able to run netEd a result of changing the SWT version or were you able to run it before?
The errors found in your log file are SWT errors, which may be due to an incompatibility somewhere, but it's hard to say. Did netEd work fine?

**Comment by mcubuktepe** [comment]
netEd works fine, thanks for the reply
